# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttk2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netcode',
            old_name='active',
            new_name='enabled',
        ),
        migrations.AddField(
            model_name='netcode',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
