# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttk2', '0002_auto_20160122_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netcode',
            name='running',
        ),
        migrations.AddField(
            model_name='netcode',
            name='curstart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=None),
        ),
    ]
