# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttk2', '0004_auto_20160127_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
